# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Gmauro
tagline:          'Personal website'
description:      'Computer scientist focusing on Bioinformatics with deep experience on data engineering and infrastructures for computing.'
url:              'https://gmauro.github.io'
baseurl:          '/'

author:
  name:           'Gianmauro Cuccuru'
  url:            https://twitter.com/

paginate:         5
paginate_path: "/blog/page:num/"
# Custom vars
version:          21.08
plugins: [jekyll-paginate]

github:
  repo:           https://github.com/gmauro/gmauro.github.io
